In [25]:
from tensorflow.keras.preprocessing.text import one_hot

In [26]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [27]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [28]:
voc_size=10000

In [29]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4113, 8292, 4713, 3157],
 [4113, 8292, 4713, 7676],
 [4113, 5171, 4713, 7371],
 [5463, 6349, 7467, 6278, 6847],
 [5463, 6349, 7467, 6278, 9255],
 [4443, 4113, 7913, 4713, 5151],
 [2011, 3529, 9301, 6278]]

In [30]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [31]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4113 8292 4713 3157]
 [   0    0    0    0 4113 8292 4713 7676]
 [   0    0    0    0 4113 5171 4713 7371]
 [   0    0    0 5463 6349 7467 6278 6847]
 [   0    0    0 5463 6349 7467 6278 9255]
 [   0    0    0 4443 4113 7913 4713 5151]
 [   0    0    0    0 2011 3529 9301 6278]]


In [32]:
dim=10

In [33]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Users/garikaptilokesh/Documents/UDEMY-MLPR/annmodel/annenv/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [34]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 253ms/step


array([[[ 0.0021469 , -0.00560147,  0.03531355, -0.04452306,
         -0.0448309 , -0.032151  , -0.02055128, -0.04882877,
         -0.02532972,  0.0011378 ],
        [ 0.0021469 , -0.00560147,  0.03531355, -0.04452306,
         -0.0448309 , -0.032151  , -0.02055128, -0.04882877,
         -0.02532972,  0.0011378 ],
        [ 0.0021469 , -0.00560147,  0.03531355, -0.04452306,
         -0.0448309 , -0.032151  , -0.02055128, -0.04882877,
         -0.02532972,  0.0011378 ],
        [ 0.0021469 , -0.00560147,  0.03531355, -0.04452306,
         -0.0448309 , -0.032151  , -0.02055128, -0.04882877,
         -0.02532972,  0.0011378 ],
        [ 0.03214595, -0.02210718,  0.03818161, -0.00871573,
         -0.04414847, -0.04606491, -0.04224977,  0.01705385,
          0.0470353 , -0.02103425],
        [-0.00792452, -0.02896394, -0.01950455,  0.0494213 ,
         -0.01029747, -0.04492699, -0.02189952,  0.02231992,
         -0.01635525,  0.00510719],
        [ 0.04786778, -0.03753328, -0.0130479 , -0.0

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 4113, 8292, 4713, 3157], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

IndexError: tuple index out of range